# Basic
title: hengliang
subtitle: ä¸ªäººç«™
description: å¿«ä¹åœ°åˆ›é€ å’Œå“å‘³ç”Ÿæ´»
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: hengliang
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: java / iOS
url: "http://wanghengliang.cn"

beianhao: "èœ€ICPå¤‡09035688å·"

# Comment
comment:
    # disqus: hengliang
    # duoshuo: hengliang 
    # cloudTie: hengliang

# Social
social:
    #weibo: 2664335333 
    github: wanghengliang
    # twitter: 
    mail: wanghengliang@outlook.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
#baidu:
#    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
#    id: UA-84134159-3   
#    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/wanghengliang/wanghengliang.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
markdown: kramdown
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}
    - {title: åˆ†ç±», description: category, url: '/category'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}
    

# Pagination,jekyll-sitemap
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


